[features]
seeds = false
skip-lint = false

[programs.localnet]
super_simple_randomness = "Dn1wLPridFoHT4Nn5xinLoh8N2N1YKpMfHpz1gkRTD4w"
switchboard_randomness_callback = "3bvUdswsFSpoD5kk9jtVakTXg21B9mLFhT1ev9LuqGo3"

[programs.devnet]
super_simple_randomness = "Dn1wLPridFoHT4Nn5xinLoh8N2N1YKpMfHpz1gkRTD4w"
switchboard_randomness_callback = "3bvUdswsFSpoD5kk9jtVakTXg21B9mLFhT1ev9LuqGo3"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
callback-flip = "tsx ./scripts/callback-flip.ts"
simple-flip = "tsx ./scripts/simple-flip.ts"
update-measurement = "tsx ./scripts/update-measurement.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[test]
startup_wait = 15000

[[test.validator.clone]] # sbv2 programID
address = "SW1TCH7qEPTdLsDHRgPuMQjbQxKdH2aBStViMFnt64f"

[[test.validator.clone]] # sbv2 IDL
address = "Fi8vncGpNKbq62gPo56G4toCehWNy77GgqGkTaAF5Lkk"

[[test.validator.clone]] # sbv2 SbState
address = "CyZuD7RPDcrqCGbNvLCyqk6Py9cEZTKmNKujfPi3ynDd"

[[test.validator.clone]] # sb attestation programID
address = "sbattyXrzedoNATfc4L31wC9Mhxsi1BmFhTiN8gDshx"

[[test.validator.clone]] # sb devnet attestation IDL
address = "5ExuoQR69trmKQfB95fDsUGsUrrChbGq9PFgt8qouncz"

[[test.validator.clone]] # sb devnet programState
address = "5MFs7RGTjLi1wtKNBFRtuLipCkkjs4YQwRRU9sjnbQbS"
